#ifndef		_HSSD_CONFIG_H_
#define		_HSSD_CONFIG_H_
//COMMON_ANOD,	 COMMON_CATHODE
#define		MODE			COMMON_ANODE

//(DIO_PORT_A, DIO_PORT_B, DIO_PORT_C, DIO_PORT_D)
#define		HSSD_PORTA		DIO_PORT_C
#define		HSSD_PORTB		DIO_PORT_C
#define		HSSD_PORTC		DIO_PORT_C
#define		HSSD_PORTD		DIO_PORT_C
#define		HSSD_PORTE		DIO_PORT_C
#define		HSSD_PORTF		DIO_PORT_C
#define		HSSD_PORTG		DIO_PORT_C
#define		HSSD_PORTDP		DIO_PORT_C

#define		HSSD_PINA		DIO_PIN0
#define		HSSD_PINB		DIO_PIN1
#define		HSSD_PINC		DIO_PIN2
#define		HSSD_PIND		DIO_PIN3
#define		HSSD_PINE		DIO_PIN4
#define		HSSD_PINF		DIO_PIN5
#define		HSSD_PING		DIO_PIN6
#define		HSSD_PINDP		DIO_PIN7


#endif
