#ifndef  _EXTI_CONFIG_H_
#define  _EXTI_CONFIG_H_

#define  EXTI_INT0			ENABLE
#define  EXTI_INT1      	DISABLE
#define  EXTI_INT2      	DISABLE

#define  SENSE_MODE_INT0 	FALLING_EDGE
#define  SENSE_MODE_INT1 	FALLING_EDGE
#define  SENSE_MODE_INT2 	FALLING_EDGE_INT2

#endif
